/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utility.ScreenBackground;
import java.awt.GridLayout;
import javax.swing.JFrame;

/**
 *
 * @author fabio
 */
public class Main extends javax.swing.JFrame {

    ScreenBackground scrt;
    ClientIntFrameform clientIntFrameform;
    
    public Main() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setLayout(new GridLayout());
        
        scrt = new ScreenBackground("img/pizza-fundo.jpg");
        getContentPane().add(scrt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Jfm_Registration = new javax.swing.JMenu();
        Jfm_Registration_Menu_Client = new javax.swing.JMenuItem();
        Jfm_Registration_Menu_Employee = new javax.swing.JMenuItem();
        Jfm_Registration_Menu_Menu = new javax.swing.JMenuItem();
        Jfm_Registration_Menu_Deliveryman = new javax.swing.JMenuItem();
        Jfm_Cashier = new javax.swing.JMenu();
        Jfm_Cashier_Request = new javax.swing.JMenuItem();
        Jfm_Report = new javax.swing.JMenu();
        Jfm_Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria FLGC");

        Jfm_Registration.setText("Cadastro");

        Jfm_Registration_Menu_Client.setText("Clientes");
        Jfm_Registration_Menu_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jfm_Registration_Menu_ClientActionPerformed(evt);
            }
        });
        Jfm_Registration.add(Jfm_Registration_Menu_Client);

        Jfm_Registration_Menu_Employee.setText("Funcionários");
        Jfm_Registration.add(Jfm_Registration_Menu_Employee);

        Jfm_Registration_Menu_Menu.setText("Cardápio");
        Jfm_Registration_Menu_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jfm_Registration_Menu_MenuActionPerformed(evt);
            }
        });
        Jfm_Registration.add(Jfm_Registration_Menu_Menu);

        Jfm_Registration_Menu_Deliveryman.setText("Entregador");
        Jfm_Registration.add(Jfm_Registration_Menu_Deliveryman);

        jMenuBar1.add(Jfm_Registration);

        Jfm_Cashier.setText("Caixa");

        Jfm_Cashier_Request.setText("Pedido");
        Jfm_Cashier.add(Jfm_Cashier_Request);

        jMenuBar1.add(Jfm_Cashier);

        Jfm_Report.setText("Relatórios");
        jMenuBar1.add(Jfm_Report);

        Jfm_Exit.setText("Sair");
        jMenuBar1.add(Jfm_Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jfm_Registration_Menu_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jfm_Registration_Menu_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jfm_Registration_Menu_MenuActionPerformed

    private void Jfm_Registration_Menu_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jfm_Registration_Menu_ClientActionPerformed
        clientIntFrameform = new ClientIntFrameform();
        scrt.add(clientIntFrameform);
        clientIntFrameform.setVisible(true);
    }//GEN-LAST:event_Jfm_Registration_Menu_ClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jfm_Cashier;
    private javax.swing.JMenuItem Jfm_Cashier_Request;
    private javax.swing.JMenu Jfm_Exit;
    private javax.swing.JMenu Jfm_Registration;
    private javax.swing.JMenuItem Jfm_Registration_Menu_Client;
    private javax.swing.JMenuItem Jfm_Registration_Menu_Deliveryman;
    private javax.swing.JMenuItem Jfm_Registration_Menu_Employee;
    private javax.swing.JMenuItem Jfm_Registration_Menu_Menu;
    private javax.swing.JMenu Jfm_Report;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
